[package]
name = "rss"
version = "0.1.0"
edition = "2021"
authors = ["Programmer-RD-AI <79456372+Programmer-RD-AI@users.noreply.github.com>"]

[lib]
crate-type = ["cdylib"]

[dependencies]
worker = { version = "0.6" }
worker-macros = { version = "0.6" }
